# Generated by Django 4.0.2 on 2022-06-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders_customer_orders_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='tags',
            field=models.ManyToManyField(to='shop.tag'),
        ),
    ]
